### ISSUE TITLE
Ubicoustics with docker

### ISSUE THREAD

**Issue by tatecarson** [FIGLAB/ubicoustics#2]
I understand this is not technically the best place to ask this but I don't know where else to ask. Feel free to close/ignore. 

I am trying to get this running inside of a docker image for portability. Perhaps you all have tried this previously? 

Here's my Dockerfile:
```
FROM ubuntu:18.04

WORKDIR /app
COPY . /app

# Install Python.
RUN \
  apt-get update && \
  apt-get install -y libasound2 libportaudio2 libportaudiocpp0 && \
  apt-get install -y ffmpeg python-pyaudio python3-pyaudio && \
  rm -rf /var/lib/apt/lists/*

RUN pip install numpy keras wget tensorflow

# CMD ["python", "example_fileprediction_simple.py"]
```
Then when I try to run the first example I get this error: 
```
root@0631636f9b8e:/app# python example_fileprediction_simple.py
Using TensorFlow backend.
=====
Checking model... 
=====
Using deep learning model: models/example_model.hdf5
Traceback (most recent call last):
  File "example_fileprediction_simple.py", line 35, in <module>
    model = load_model(trained_model)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/base_layer.py", line 1109, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```

There must be something I'm missing with the installation process. I got it working with your instructions and virtualenv but I am trying to deploy it online so I need docker. 

Thanks.

**Comment by gierad** [comment]
Docker support would be great. Give me a couple days to figure this out. Will get back to you shortly.

**Comment by gierad** [comment]
@tatecarson can you send us your Dockerfile? We were able to run Ubicoustics using this Docker setup: https://gist.github.com/ArkaneCow/3df149298a9cbfd6b928faab0fa40045.  That environment uses `python3.6` and `tensorflow-gpu` (although tensorflow-gpu is not required).

**Comment by tatecarson** [comment]
That was the Dockerfile in the comment above. I tried to follow the same steps that you laid out for virtualenv. 

I will try your Dockerfile. Should it work to run this from the main git repo? Also, I noticed that your Dockerfile does not install pyaudio and I was wondering what the reason was.

**Comment by gierad** [comment]
I see. @ArkaneCow (who used Docker) used Ubicoustics for offline analysis, and not a live microphone. That's why his Docker file doesn't include `pyaudio`.

I'm not super familiar with Docker and its intricacies. In the past, have you tried to successfully use a microphone from a Docker container? (I haven't)

Finally, try forcing `pip` to install the following modules :
`pip install numpy==1.14.1 tensorflow==1.5.0 keras==2.1.6 wget`

That setup worked for my environment. My general next step, is to figure out how to upgrade those dependencies to leverage the latest version of `numpy`, `keras`, and `tensorflow`.

**Comment by gierad** [comment]
Someone suggested the following Docker config for accessing the mic on Ubuntu:
`docker run --device /dev/snd:/dev/snd <container_name>`

Source:
https://stackoverflow.com/questions/45700653/can-my-docker-container-app-access-the-hosts-microphone-and-speaker-mac-wind/48795232#48795232

**Comment by tatecarson** [comment]
Thank you for the comments. I was actually trying to deploy ubicoustics as a web app and send audio into it using the Web Audio API. I will send you all some documentation when I finish if it is of any interest to you.

**Comment by gierad** [comment]
Sounds great, and you're welcome to send it along!
